version: '3.5'
services:
  database:
    image: 'postgres:15.2'
    container_name: database-sbk
    ports:
      - '15432:5432'
    environment:
      - 'POSTGRES_USER=myuser'
      - 'POSTGRES_DB=mydatabase'
      - 'POSTGRES_PASSWORD=secret'
