spring:
  datasource:
    url: jdbc:postgresql://localhost:15432/mydatabase
    username: myuser
    password: secret
  docker:
    compose:
      enabled: true
      file:
        - postgres-compose.yaml
        - kafka-compose.yaml
      stop:
        command: down
        timeout: 20s
  jpa:
    hibernate:
      ddl-auto: create