spring:
  application:
    name: spring-boot-kafka
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.DelegatingByTopicSerializer
      # This is the main bit signalling transactionality
      transaction-id-prefix: kafka-tx-
      properties:
        schema.registry.url: http://localhost:8081
        spring.kafka.value.serialization.bytopic.default: org.apache.kafka.common.serialization.StringSerializer
        spring.kafka.value.serialization.bytopic.config: "${app.kafka.orders-topic-name}:io.confluent.kafka.serializers.KafkaAvroSerializer"
      # to ensure that the producer waits for all replicas to acknowledge the write before considering it successful
      acks: all
      retries: 3

    consumer:
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
#      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.DelegatingByTopicDeserializer
      group-id: ${spring.application.name}-group
      auto-offset-reset: earliest
      properties:
        isolation.level: read_committed
        schema.registry.url: http://localhost:8081
        specific.avro.reader: true
        spring.kafka.value.serialization.bytopic.default: org.apache.kafka.common.serialization.StringDeserializer
        spring.kafka.value.serialization.bytopic.config: "${app.kafka.orders-topic-name}:io.confluent.kafka.serializers.KafkaAvroDeserializer"

  logging:
    level:
      root: info
      me.mikael: debug
      org.springframework.transaction: trace
      org.springframework.kafka.transaction: debug

app:
  kafka:
    source-topic-name: me-mikael-kafka-source-v001
    orders-topic-name: me-mikael-kafka-orders-v001